# Kubernetes Manifest Contracts
# Feature: 005-kubernetes-deployment
# Date: 2026-01-14
#
# This file defines the expected structure of Kubernetes manifests.
# Actual manifests will be created in infra/k8s/ during implementation.
#
# Use: kubectl apply --dry-run=client -f <manifest> to validate against these contracts

---
# Contract: Namespace + ServiceAccount
apiVersion: v1
kind: Namespace
metadata:
  name: claude-agent
  labels:
    app: claude-code-agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: claude-agent-sa
  namespace: claude-agent
  annotations:
    azure.workload.identity/client-id: "866b8e62-d9ce-42d1-a6b0-4382baf39f7a"
  labels:
    azure.workload.identity/use: "true"
---
# Contract: NetworkPolicy - Default Deny All
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: claude-agent
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
# Contract: NetworkPolicy - Allow DNS
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: claude-agent
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
# Contract: NetworkPolicy - Allow Azure Egress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-azure-egress
  namespace: claude-agent
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - ports:
        - protocol: TCP
          port: 443
---
# Contract: NetworkPolicy - Allow n8n Ingress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-n8n
  namespace: claude-agent
spec:
  podSelector:
    matchLabels:
      app: claude-code-agent
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: n8n-prod
          podSelector:
            matchLabels:
              app: n8n
      ports:
        - protocol: TCP
          port: 3000
---
# Contract: SecretProviderClass for GitHub App
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: github-app-akv
  namespace: claude-agent
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "866b8e62-d9ce-42d1-a6b0-4382baf39f7a"
    keyvaultName: "iius-akv"
    tenantId: "${AZURE_TENANT_ID}"  # Replace during implementation
    objects: |
      array:
        - |
          objectName: github-app-id
          objectType: secret
          objectAlias: app-id
        - |
          objectName: github-app-private-key
          objectType: secret
          objectAlias: private-key.pem
---
# Contract: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: claude-code-agent
  namespace: claude-agent
  labels:
    app: claude-code-agent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: claude-code-agent
  template:
    metadata:
      labels:
        app: claude-code-agent
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: claude-agent-sa
      terminationGracePeriodSeconds: 120
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault

      initContainers:
        - name: copy-claude-session
          image: busybox:1.36
          command: ['sh', '-c', 'cp -r /claude-session-ro/. /home/claude-agent/.claude/ && chown -R 1001:1001 /home/claude-agent/.claude']
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
          volumeMounts:
            - name: claude-session
              mountPath: /claude-session-ro
              readOnly: true
            - name: claude-home
              mountPath: /home/claude-agent/.claude

      containers:
        - name: claude-agent
          image: iiusacr.azurecr.io/claude-agent:v4.6.2
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              memory: "1Gi"

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TEAMS_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: teams-webhook
                  key: url

          volumeMounts:
            - name: claude-home
              mountPath: /home/claude-agent/.claude
            - name: azure-home
              mountPath: /home/claude-agent/.azure
            - name: tmp
              mountPath: /tmp
            - name: workspace
              mountPath: /workspace
            - name: github-secrets
              mountPath: /secrets/github
              readOnly: true

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]

      volumes:
        - name: claude-session
          secret:
            secretName: claude-session
        - name: claude-home
          emptyDir: {}
        - name: azure-home
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: workspace
          emptyDir: {}
        - name: github-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: github-app-akv
---
# Contract: Service
apiVersion: v1
kind: Service
metadata:
  name: claude-agent
  namespace: claude-agent
  labels:
    app: claude-code-agent
spec:
  type: ClusterIP
  selector:
    app: claude-code-agent
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
